"""Deterministic, continuous-phase frequency-error impairments.

The sign convention is positive-Q: a positive instantaneous frequency error
rotates a complex sample counter-clockwise and is reported by ``wsprd`` as a
higher received frequency.  Phase is accumulated from the sample-wise
instantaneous frequency; no independent per-sample phase jumps are applied.
"""

from __future__ import annotations

import math
from typing import Sequence


def apply_frequency_error(
    samples: Sequence[complex],
    delta_f_hz: Sequence[float],
    sample_rate_hz: float,
    *,
    initial_phase_rad: float = 0.0,
) -> tuple[complex, ...]:
    """Multiply samples by the phasor generated by ``delta_f_hz``.

    Output sample ``n`` uses the phase at the start of its sample interval;
    its frequency advances the phase used by sample ``n + 1``.  This is the
    left-endpoint discrete integral of instantaneous frequency.
    """

    if len(samples) != len(delta_f_hz):
        raise ValueError("samples and delta_f_hz must have equal length")
    if not math.isfinite(sample_rate_hz) or sample_rate_hz <= 0:
        raise ValueError("sample_rate_hz must be finite and positive")
    if not math.isfinite(initial_phase_rad):
        raise ValueError("initial_phase_rad must be finite")

    phase = float(initial_phase_rad)
    scale = math.tau / float(sample_rate_hz)
    output: list[complex] = []
    for sample, frequency in zip(samples, delta_f_hz):
        frequency = float(frequency)
        if not math.isfinite(frequency):
            raise ValueError("all frequency-error samples must be finite")
        phasor = complex(math.cos(phase), math.sin(phase))
        output.append(complex(sample) * phasor)
        phase += scale * frequency
    return tuple(output)


def constant_cfo_trajectory(sample_count: int, cfo_hz: float) -> tuple[float, ...]:
    """Return a constant instantaneous frequency offset in hertz."""

    if sample_count < 0 or not math.isfinite(cfo_hz):
        raise ValueError("invalid sample_count or cfo_hz")
    return (float(cfo_hz),) * sample_count


def linear_drift_trajectory(sample_count: int, total_drift_hz: float) -> tuple[float, ...]:
    """Return a centered linear trajectory from -drift/2 to +drift/2.

    ``total_drift_hz`` is the end-minus-start frequency change across the
    active frame.  Positive drift means increasing frequency with time.
    """

    if sample_count <= 0 or not math.isfinite(total_drift_hz):
        raise ValueError("sample_count must be positive and drift finite")
    if sample_count == 1:
        return (0.0,)
    return tuple(
        float(total_drift_hz) * (index / (sample_count - 1) - 0.5)
        for index in range(sample_count)
    )


def wsprd_linear_drift_trajectory(
    symbol_count: int, samples_per_symbol: int, drift_parameter_hz: float
) -> tuple[float, ...]:
    """Reproduce the production wsprd symbolwise linear-drift definition.

    For symbol index ``i``, wsprd searches
    ``(drift/2) * (i - symbol_count/2) / (symbol_count/2)`` hertz relative
    to its center-frequency estimate. Thus for 162 symbols the actual
    first-to-last change is ``161/162 * drift``. Frequency is constant within
    each symbol while accumulated phase stays continuous at the boundaries.
    """

    if symbol_count <= 0 or samples_per_symbol <= 0 or not math.isfinite(drift_parameter_hz):
        raise ValueError("symbol sizes must be positive and drift finite")
    midpoint = symbol_count / 2.0
    values: list[float] = []
    for index in range(symbol_count):
        frequency = (float(drift_parameter_hz) / 2.0) * (index - midpoint) / midpoint
        values.extend((frequency,) * samples_per_symbol)
    return tuple(values)


def exact_wsprd_linear_drift_trajectory(
    symbol_count: int, samples_per_symbol: int, drift_parameter_hz: float
) -> tuple[float, ...]:
    """Generate exact WSPR-d linear drift trajectory matching wsprd formula.

    Formula: delta_f[i] = (drift/2) * (i - 81) / 81
    for i = 0..161

    This function implements the exact same formula used in production wsprd
    to ensure perfect compatibility.
    """

    if symbol_count <= 0 or samples_per_symbol <= 0 or not math.isfinite(drift_parameter_hz):
        raise ValueError("symbol sizes must be positive and drift finite")
    
    # Generate symbol-level trajectory using exact WSPR-d formula
    values: list[float] = []
    for index in range(symbol_count):
        frequency = (float(drift_parameter_hz) / 2.0) * (index - 81) / 81.0
        values.extend((frequency,) * samples_per_symbol)
    return tuple(values)


def wspr_symbol_quadratic_residual_trajectory(
    n_symbols: int = 162,
    samples_per_symbol: int = 256,
    amplitude_hz: float = 0.0,
) -> tuple[float, ...]:
    """Symbolwise quadratic orthogonal to constant and linear frequency."""

    if n_symbols != 162 or samples_per_symbol <= 0:
        raise ValueError("pilot requires 162 symbols and positive samples_per_symbol")
    if not math.isfinite(amplitude_hz) or amplitude_hz < 0:
        raise ValueError("amplitude_hz must be finite and nonnegative")
    import numpy as np

    x = (np.arange(n_symbols) - 81.0) / 81.0
    basis = np.column_stack([np.ones_like(x), x])
    beta = np.linalg.lstsq(basis, x**2, rcond=None)[0]
    q_perp = x**2 - basis @ beta
    q_norm = q_perp / np.max(np.abs(q_perp))
    symbols = tuple(float(value) for value in amplitude_hz * q_norm)
    return tuple(value for symbol in symbols for value in (symbol,) * samples_per_symbol)


def quadratic_residual_trajectory(sample_count: int, a_res_hz: float) -> tuple[float, ...]:
    """Return a centered quadratic residual normalized to ``max(abs(f))``.

    The least-squares constant and linear terms are removed on the discrete
    active-frame sample grid.  The returned trajectory is therefore already
    orthogonal to the decoder's constant-plus-linear model.  This oracle
    calculation defines severity only; it is not supplied to the decoder.
    """

    if sample_count < 3 or not math.isfinite(a_res_hz) or a_res_hz < 0:
        raise ValueError("sample_count must be >=3 and a_res_hz finite and nonnegative")
    if a_res_hz == 0:
        return (0.0,) * sample_count
    center = (sample_count - 1) / 2.0
    x = tuple((index - center) / center for index in range(sample_count))
    raw = tuple(value * value for value in x)
    mean_x = sum(x) / sample_count
    mean_raw = sum(raw) / sample_count
    covariance = sum((xi - mean_x) * (yi - mean_raw) for xi, yi in zip(x, raw))
    variance = sum((xi - mean_x) ** 2 for xi in x)
    slope = covariance / variance
    intercept = mean_raw - slope * mean_x
    residual = tuple(yi - (intercept + slope * xi) for xi, yi in zip(x, raw))
    peak = max(abs(value) for value in residual)
    return tuple(float(a_res_hz) * value / peak for value in residual)


def embed_active_trajectory(
    total_sample_count: int,
    frame_start_sample: int,
    active_trajectory_hz: Sequence[float],
) -> tuple[float, ...]:
    """Place an active-frame trajectory in a zero-error container."""

    end = frame_start_sample + len(active_trajectory_hz)
    if frame_start_sample < 0 or end > total_sample_count:
        raise ValueError("active trajectory does not fit in container")
    return (
        (0.0,) * frame_start_sample
        + tuple(float(value) for value in active_trajectory_hz)
        + (0.0,) * (total_sample_count - end)
    )
